### ISSUE TITLE
ClientLogin is disabled, need to upgrade to OAuth 2.0

### ISSUE THREAD

**Issue by dschwen** [michael-adler/sync-google-contacts#10]
Google deprecated and disabled the password based authentication. This script need to be updated to utilize OAuth 2.0.

**Comment by dschwen** [comment]
0fcca64 makes a browser pop up to authenticate the app (needs a client secret generated at https://console.developers.google.com/project with type _installed_ application). However when utilizing the API it complains about the user not being authenticated. I'll investigate further.

**Comment by dschwen** [comment]
I saw @dkelley044 had already implemented a working version of this. I changed the directores and the README a bit.

**Comment by dkelley044** [comment]
I'd love for someone to pretty up my work and help me solve a couple
problems I'm having. do you have the skills to help?
1. I need to modify the feed I'm returning to google as far as XML
namespace schemas for contacts. google contacts that link to a google+
profile and/or contacts that are modified in some contexts contain xml
extended attribute tags with NS3, which outlook google sync chokes on. they
are extraneous tags and not needed, so I'd like to mark any contacts that
contain NS3 with an updated timestamp and flag them as updated in the sync
script, strip the NS3 tags or modify to include appropriate XML namespace
tags, and then return the updated XML /modify that contact for all users
selected in that run, instead of just modifying the incoming XML with the
atom client parse string replacement.
2. I'd like to find a way to synchronize contact photos between accounts -
is this possible?

**Comment by mrmattwilkins** [comment]
Hi there,
Are you still maintaining this?  I hope so, because I have patched it up so google-contacts-sync now works with oauth2!  AFAIK this is the only open source freely available bit of code that can sync google contacts.  I tried ASynk and it was a buggy.  So could you roll in the patch?  There is also an extra doco file to help with setting up credentials.
[README-google-oauth2.txt](https://github.com/michael-adler/sync-google-contacts/files/299245/README-google-oauth2.txt)
[patch.txt](https://github.com/michael-adler/sync-google-contacts/files/299246/patch.txt)

**Comment by mrmattwilkins** [comment]
Just a small update on the READ-google-oauth2.txt file.  The keyfile and credfile options must be full path names

**Comment by dschwen** [comment]
Uuuaaahhhh! Thank you! I took a stab at this two weeks ago and have up. The
state of Google oauth documentation one of the most frustrating development
experiences I've had in a long time.

**Comment by dkelley044** [comment]
I've been running it daily for 15+ accounts and 2000+ contacts and it seems
to be working.
Please bear in mind I originally wrote my oauth2 patch to run on a headless
server, hence why the original oauth2 prompts output to shell/console the
URL for verification and wait for input of verification key. I haven't had
any issues with having to re-authorize after initial setup.




On Sun, Jun 5, 2016 at 9:30 AM, Daniel Schwen <notifications@github.com>
wrote:

> Uuuaaahhhh! Thank you! I took a stab at this two weeks ago and have up. The
> state of Google oauth documentation one of the most frustrating development
> experiences I've had in a long time.
>
> On Sun, Jun 5, 2016, 2:28 AM mrmattwilkins <notifications@github.com>
> wrote:
>
> > Just a small update on the READ-google-oauth2.txt file. The keyfile and
> > credfile options must be full path names
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/michael-adler/sync-google-contacts/issues/10#issuecomment-223799907
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AAMWPko92sprVn88KPpkJoV-qe7Dw_XHks5qIojHgaJpZM4FWcDD
> >
> > .
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/michael-adler/sync-google-contacts/issues/10#issuecomment-223822645>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMKqFETCp0zfxSZdsoHgJ8qN4YrFgsTuks5qIvmVgaJpZM4FWcDD>
> .
>



-- 
David Kelley
Superintendent @ PROBuild Contractors, LLC - dkelley@probuildor.com
Independent Technology Consultant - dkelley044@gmail.com
(503) 405-6500

**Comment by mrmattwilkins** [comment]
Yeah I agree: oauth2, what a nightmare!  In the end I didn't have to add
much code at all, it just took forever to find doco that was up to date
with a nice example.

**Comment by michael-adler** [comment]
Finally committed the change to support OAuth

**Comment by mrmattwilkins** [comment]
Awesome better later than never!  Thanks.
